[package]
name = "ft_otp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
crypto = "0.5.1"
env_logger = "0.11.3"
log = "0.4.21"
ring = "0.17.0"
base32 = "0.4"